nyc_taxi_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: nyc-taxi-462721
      dataset: nyc_taxi_dbt
      keyfile: /home/runner/gcp-creds.json
      threads: 4
      timeout_seconds: 300
      location: US

