name: dbt CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      # 1 Check out repo
      - uses: actions/checkout@v3

      # 2 Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3 Install dbt‑bigquery
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-core~=1.10.0" "dbt-bigquery~=1.10.0"

      # 4 Write GCP credentials from secret
      - name: Write GCP credentials
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > $HOME/gcp-creds.json

      # 5 Run dbt
      - name: Run dbt
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.home }}/gcp-creds.json
        run: |
          dbt deps
          dbt seed   --profiles-dir . --target dev
          dbt run    --profiles-dir . --target dev
          dbt test   --profiles-dir . --target dev
